# Generated by Django 5.1.3 on 2025-01-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('eventname', models.TextField()),
                ('eventdate', models.DateField()),
                ('venue', models.TextField()),
                ('maxattendees', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participantid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('participantname', models.CharField(max_length=20)),
                ('participantphone', models.CharField(max_length=10)),
                ('participantemail', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationdate', models.DateField()),
                ('ticketnumber', models.CharField(max_length=7)),
                ('amountpaid', models.CharField(max_length=3)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEvents.events')),
                ('participantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEvents.participants')),
            ],
        ),
    ]
