# Generated by Django 5.1.3 on 2025-01-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEvents', '0002_alter_events_maxattendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='amountpaid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='ticketnumber',
            field=models.CharField(max_length=10),
        ),
    ]
