# Generated by Django 5.1.3 on 2025-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEvents', '0003_alter_registrations_amountpaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventstatus',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
    ]
